/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Random;

public class Library {

  public int[] roll(int numberOfRolls) {
    Random randomNumberGenerator = new Random();

    int[] rollResults = new int[numberOfRolls];

    for (int i = 0; i < numberOfRolls; i++) {
      rollResults[i] = randomNumberGenerator.nextInt(6) + 1;
    }
    return rollResults;
  }

  public boolean containsDuplicates(int[] Arr) {
    for (int i = 0; i < Arr.length - 1; i++) {
      //what a nightmare this is, I haven't thought about nested for-loops in a month
      for (int j = i + 1; j < Arr.length; j++) {
        if (Arr[i] == Arr[j]) {
          return true;
        }
      }
    }
    return false;
  }

  public double average(int[] arr) {
    int total = 0;

    for (int i = 0; i < arr.length; i++) {
      total = total + arr[i];
    }
    return (double) total / arr.length;
  }

  public int[] lowestAverage(int[][] arrays) {
    int minIndex = 0;

    double minAverage = Double.MAX_VALUE;

    for (int i = 0; i < arrays.length; i++) {
      double currentAverage = average(arrays[i]);

      if (currentAverage < minAverage) {
        minIndex = i;
        minAverage = currentAverage;
      }
    }
    return arrays[minIndex];
  }
}


